export const initialData = [
  {
    id: 1,
    title: "Launch Epic Career 🚀",
    description: "",
    status: "to-do",
    board: "Launch Career",
  },
  {
    id: 2,
    title: "Conquer React⚛️",
    description: "",
    status: "to-do",
    board: "Launch Career",
  },
  {
    id: 3,
    title: "Understand Databases⚙️",
    description: "",
    status: "to-do",
    board: "Launch Career",
  },
  {
    id: 4,
    title: "Crush Frameworks🖼️",
    description: "",
    status: "to-do",
    board: "Launch Career",
  },
  {
    id: 5,
    title: "Master JavaScript 💛",
    description: "",
    status: "in-progress",
    board: "Launch Career",
  },
  {
    id: 6,
    title: "Never Give Up 🏆",
    description: "",
    status: "in-progress",
    board: "Launch Career",
  },
  {
    id: 7,
    title: "Explore ES6 Features 🚀",
    description: "",
    status: "done",
    board: "Launch Career",
  },
  {
    id: 8,
    title: "Have fun 🥳",
    description: "",
    status: "done",
    board: "Launch Career",
  },
];
